# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\"c\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"a\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x02(\t\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x17\n\x06status\x18\x03 \x01(\x0e\x32\x07.StatusB\x06\n\x04type\"p\n\x11\x43reateBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\";\n\x12\x43reateBookResponse\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\x12\x17\n\x0f\x65rror_message_1\x18\x02 \x01(\t\"\xa0\x01\n\x0fGetBookResponse\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\x12\x17\n\x06status\x18\x06 \x01(\x0e\x32\x07.Status\x12\x17\n\x0f\x65rror_message_2\x18\x07 \x01(\t*4\n\x05Genre\x12\x0b\n\x07HISTORY\x10\x00\x12\x12\n\x0eMURDER_MYSTERY\x10\x01\x12\n\n\x06\x43OMICS\x10\x02*1\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x12\r\n\tUNDEFINED\x10\x02\x32{\n\x10InventoryService\x12\x37\n\nCreateBook\x12\x12.CreateBookRequest\x1a\x13.CreateBookResponse\"\x00\x12.\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x10.GetBookResponse\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=587
  _GENRE._serialized_end=639
  _STATUS._serialized_start=641
  _STATUS._serialized_end=690
  _BOOK._serialized_start=17
  _BOOK._serialized_end=116
  _INVENTORYITEM._serialized_start=118
  _INVENTORYITEM._serialized_end=215
  _CREATEBOOKREQUEST._serialized_start=217
  _CREATEBOOKREQUEST._serialized_end=329
  _GETBOOKREQUEST._serialized_start=331
  _GETBOOKREQUEST._serialized_end=361
  _CREATEBOOKRESPONSE._serialized_start=363
  _CREATEBOOKRESPONSE._serialized_end=422
  _GETBOOKRESPONSE._serialized_start=425
  _GETBOOKRESPONSE._serialized_end=585
  _INVENTORYSERVICE._serialized_start=692
  _INVENTORYSERVICE._serialized_end=815
# @@protoc_insertion_point(module_scope)
